//
//  PuzzleCollectionViewLayout+Constants.swift
//  PuzzleLayout
//
//  Created by Yossi Avramov on 05/10/2016.
//  Copyright © 2016 Houzz. All rights reserved.
//

import UIKit

/// An element kind for separator line. Shouldn't be used by 'PuzzlePieceSectionLayout' since separator lines generated by 'PuzzleCollectionViewLayout'
public let PuzzleCollectionElementKindSeparatorLine = "!_SeparatorLine_!"

/// An element kind for top gutter
public let PuzzleCollectionElementKindSectionTopGutter = "!_SectionTopGutter_!"

/// An element kind for bottom gutter
public let PuzzleCollectionElementKindSectionBottomGutter = "!_SectionBottomGutter_!"

/// A key used to set the view background color for separator lines & gutters.
public let PuzzleCollectionColoredViewColorKey = "!_BackgroundColor_!"

/// An element kind for 'PuzzleCollectionViewLayout' headers. This string is equal to the flow layout element kind for headers, which makes it easy to create header in storyboard.
public let PuzzleCollectionElementKindSectionHeader: String = UICollectionElementKindSectionHeader

/// An element kind for 'PuzzleCollectionViewLayout' footers. This string is equal to the flow layout element kind for footers, which makes it easy to create footer in storyboard.
public let PuzzleCollectionElementKindSectionFooter: String = UICollectionElementKindSectionFooter

/// A Z index of separator lines, top & bottom gutters
public let PuzzleCollectionSeparatorsViewZIndex = 2

/// A Z index of pinned headers & footers
public let PuzzleCollectionHeaderFooterZIndex = 4
